### ISSUE TITLE
Add about page copy for Opportunities program

### ISSUE THREAD

**Issue by grant-king** [readytechpro/rtp-media#4]
#### Description
We need some initial copy to put on the about page for the Opportunities program. This copy should attempt to describe some of our plans for this program to a general audience. 

#### Files
Use the internal document containing the narratives for our our exempt activities to find details about this program.

#### Tasks
- [x] convert placeholder document to .md format
- [x] translate details from our internal documents to public copy
  - [x] a sentence or two about the purpose of this program
  - [x] a short list of the general features/services of this program
  - [x] any relevant information about which different aspects of this program different users are likely get involved with, depending on where they are at in their development.

- [x] add link to our Volunteer Projects page
- [x] add call to initial volunteers with links to our email, contact page, and community page.
